import type { CelestialObject } from "./types"

export const celestialObjects: CelestialObject[] = [
  {
    id: "g2v-main-sequence-star",
    name: "G2V Main Sequence Star",
    type: "star",
    subtype: "main_sequence",
    description: "A yellow main sequence star like our Sun.",
    properties: [
      { id: "objectScale", label: "Object Scale", type: "slider", min: 0.1, max: 5, step: 0.1, value: 1 },
      { id: "shaderScale", label: "Shader Scale", type: "slider", min: 0.1, max: 2, step: 0.1, value: 1 },
    ],
  },
  {
    id: "m2v-red-dwarf",
    name: "M2V Red Dwarf",
    type: "star",
    subtype: "red_dwarf",
    description: "A small, cool red dwarf star.",
    properties: [
      { id: "objectScale", label: "Object Scale", type: "slider", min: 0.1, max: 5, step: 0.1, value: 0.5 },
      { id: "shaderScale", label: "Shader Scale", type: "slider", min: 0.1, max: 2, step: 0.1, value: 1 },
    ],
  },
  {
    id: "terrestrial-rocky-planet",
    name: "Terrestrial Rocky Planet",
    type: "terrestrial",
    subtype: "rocky",
    description: "An Earth-like rocky planet with atmosphere.",
    properties: [
      { id: "objectScale", label: "Object Scale", type: "slider", min: 0.1, max: 5, step: 0.1, value: 1 },
      {
        id: "landWaterRatio",
        label: "Land/Water Ratio",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.7,
        unit: "%",
      },
      { id: "temperature", label: "Temperature", type: "slider", min: 0, max: 100, step: 1, value: 50, unit: "°C" },
      {
        id: "atmosphereDensity",
        label: "Atmosphere Density",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.5,
        unit: "%",
      },
      {
        id: "atmosphereComposition",
        label: "Atmosphere Composition",
        type: "select",
        options: [
          { value: "nitrogen-oxygen", label: "Nitrogen-Oxygen" },
          { value: "carbon-dioxide", label: "Carbon Dioxide" },
          { value: "methane", label: "Methane" },
        ],
        value: "nitrogen-oxygen",
      },
      {
        id: "volcanismLevel",
        label: "Volcanism Level",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.1,
        unit: "%",
      },
      {
        id: "civilizationPresence",
        label: "Civilization Presence",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.3,
        unit: "%",
      },
    ],
  },
  {
    id: "oceanic-planet",
    name: "Oceanic Planet",
    type: "terrestrial",
    subtype: "oceanic",
    description: "A water-rich world with global oceans.",
    properties: [
      { id: "objectScale", label: "Object Scale", type: "slider", min: 0.1, max: 5, step: 0.1, value: 1 },
      {
        id: "landWaterRatio",
        label: "Land/Water Ratio",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.1,
        unit: "%",
      },
      { id: "temperature", label: "Temperature", type: "slider", min: 0, max: 100, step: 1, value: 40, unit: "°C" },
      {
        id: "atmosphereDensity",
        label: "Atmosphere Density",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.7,
        unit: "%",
      },
      {
        id: "atmosphereComposition",
        label: "Atmosphere Composition",
        type: "select",
        options: [
          { value: "nitrogen-oxygen", label: "Nitrogen-Oxygen" },
          { value: "carbon-dioxide", label: "Carbon Dioxide" },
          { value: "methane", label: "Methane" },
        ],
        value: "nitrogen-oxygen",
      },
      {
        id: "volcanismLevel",
        label: "Volcanism Level",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.05,
        unit: "%",
      },
      {
        id: "civilizationPresence",
        label: "Civilization Presence",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.2,
        unit: "%",
      },
    ],
  },
  {
    id: "smog-planet",
    name: "Smog Planet",
    type: "terrestrial",
    subtype: "smog",
    description: "A Venus-like world with thick atmosphere.",
    properties: [
      { id: "objectScale", label: "Object Scale", type: "slider", min: 0.1, max: 5, step: 0.1, value: 1 },
      {
        id: "landWaterRatio",
        label: "Land/Water Ratio",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.9,
        unit: "%",
      },
      { id: "temperature", label: "Temperature", type: "slider", min: 0, max: 100, step: 1, value: 90, unit: "°C" },
      {
        id: "atmosphereDensity",
        label: "Atmosphere Density",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.9,
        unit: "%",
      },
      {
        id: "atmosphereComposition",
        label: "Atmosphere Composition",
        type: "select",
        options: [
          { value: "nitrogen-oxygen", label: "Nitrogen-Oxygen" },
          { value: "carbon-dioxide", label: "Carbon Dioxide" },
          { value: "methane", label: "Methane" },
        ],
        value: "carbon-dioxide",
      },
      {
        id: "volcanismLevel",
        label: "Volcanism Level",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.3,
        unit: "%",
      },
      {
        id: "civilizationPresence",
        label: "Civilization Presence",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.05,
        unit: "%",
      },
    ],
  },
  {
    id: "gas-giant-jovian",
    name: "Gas Giant",
    type: "gasGiant",
    subtype: "jovian",
    description: "A massive Jupiter-like planet.",
    properties: [
      { id: "objectScale", label: "Object Scale", type: "slider", min: 0.1, max: 5, step: 0.1, value: 2 },
      { id: "ringDensity", label: "Ring Density", type: "slider", min: 0, max: 1, step: 0.01, value: 0.5, unit: "%" },
      {
        id: "ringInnerRadius",
        label: "Ring Inner Radius",
        type: "slider",
        min: 1.5,
        max: 3,
        step: 0.1,
        value: 1.8,
        unit: "x",
      },
      {
        id: "ringOuterRadius",
        label: "Ring Outer Radius",
        type: "slider",
        min: 3,
        max: 6,
        step: 0.1,
        value: 4,
        unit: "x",
      },
      {
        id: "gasComposition",
        label: "Gas Composition",
        type: "select",
        options: [
          { value: "ammonia", label: "Ammonia (I)" },
          { value: "water", label: "Water (II)" },
          { value: "cloudless", label: "Cloudless (III)" },
          { value: "alkali-metal", label: "Alkali-metal (IV)" },
          { value: "silicate", label: "Silicate (V)" },
        ],
        value: "ammonia",
      },
      {
        id: "temperatureClass",
        label: "Temperature Class",
        type: "select",
        options: [
          { value: "cold", label: "Cold" },
          { value: "temperate", label: "Temperate" },
          { value: "hot", label: "Hot Jupiter" },
        ],
        value: "temperate",
      },
    ],
  },
  {
    id: "ice-giant",
    name: "Ice Giant",
    type: "gasGiant",
    subtype: "iceGiant",
    description: "A Neptune-like planet with icy composition.",
    properties: [
      { id: "objectScale", label: "Object Scale", type: "slider", min: 0.1, max: 5, step: 0.1, value: 1.5 },
      { id: "ringDensity", label: "Ring Density", type: "slider", min: 0, max: 1, step: 0.01, value: 0.2, unit: "%" },
      {
        id: "ringInnerRadius",
        label: "Ring Inner Radius",
        type: "slider",
        min: 1.2,
        max: 2.5,
        step: 0.1,
        value: 1.5,
        unit: "x",
      },
      {
        id: "ringOuterRadius",
        label: "Ring Outer Radius",
        type: "slider",
        min: 2.5,
        max: 5,
        step: 0.1,
        value: 3,
        unit: "x",
      },
      {
        id: "gasComposition",
        label: "Gas Composition",
        type: "select",
        options: [
          { value: "ammonia", label: "Ammonia (I)" },
          { value: "water", label: "Water (II)" },
          { value: "cloudless", label: "Cloudless (III)" },
          { value: "alkali-metal", label: "Alkali-metal (IV)" },
          { value: "silicate", label: "Silicate (V)" },
        ],
        value: "water",
      },
      {
        id: "temperatureClass",
        label: "Temperature Class",
        type: "select",
        options: [
          { value: "cold", label: "Cold" },
          { value: "temperate", label: "Temperate" },
          { value: "hot", label: "Hot Jupiter" },
        ],
        value: "cold",
      },
    ],
  },
  {
    id: "black-hole",
    name: "Black Hole",
    type: "special",
    subtype: "blackHole",
    description: "Advanced black hole with gravitational lensing and realistic accretion disk.",
    properties: [
      { id: "objectScale", label: "Object Scale", type: "slider", min: 0.1, max: 5, step: 0.1, value: 1.5 },
      {
        id: "intensity",
        label: "Intensity",
        type: "slider",
        min: 0.1,
        max: 3.0,
        step: 0.1,
        value: 1.0,
        unit: "x",
      },
      {
        id: "distortion",
        label: "Gravitational Distortion",
        type: "slider",
        min: 0.1,
        max: 5.0,
        step: 0.1,
        value: 1.0,
        unit: "x",
      },
    ],
  },
  {
    id: "protostar-dusty-nebula",
    name: "Protostar (Dusty Nebula)",
    type: "special",
    subtype: "protostar",
    description: "A young star forming within a dense cloud of gas and dust.",
    properties: [
      { id: "objectScale", label: "Object Scale", type: "slider", min: 0.5, max: 10, step: 0.1, value: 3 },
      { id: "density", label: "Nebula Density", type: "slider", min: 0.01, max: 0.3, step: 0.005, value: 0.185 },
      { id: "starBrightness", label: "Star Brightness", type: "slider", min: 1, max: 50, step: 1, value: 30 },
      { id: "starHue", label: "Star Hue", type: "slider", min: 0, max: 1, step: 0.01, value: 0.08 }, // 0 (red) to 1 (violet)
      { id: "nebulaHue", label: "Nebula Hue", type: "slider", min: 0, max: 1, step: 0.01, value: 0.6 }, // 0 (red) to 1 (violet)
      { id: "rotationSpeed", label: "Rotation Speed", type: "slider", min: 0, max: 0.5, step: 0.01, value: 0.1 },
    ],
  },
]
